name: appsmith-cd  # Workflow name

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  deploy-appsmith:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - run: "curl --location --fail-early --request POST https://internal.appsmith.com/api/v1/git/deploy/app/669e604aae21844540eb5895?branchName=master --header 'Authorization: Bearer ${{ secrets.APPSMITH_CD_KEY }}'"
